---
references:
  - "File: /gs_sadoc_c4.mmd"
generationTime: 2025-11-13T17:10:34.959Z
id: 17b7486c-3714-48b5-b8ff-2c8dc05ae338

author: "Can Deniz Kaya"
role: "TIR Instrument Engineer"
title: 'L1 Production Flowchart'
company: "Starion"
contractor: "ESA ESRIN"
date: "13.11.2025"

config:
  theme: 'base'
  themeVariables:
    primaryColor: '#BB2528'
    primaryTextColor: '#fff'
    primaryBorderColor: '#7C0000'
    lineColor: '#32d30aff'
    secondaryColor: '#006100'
    tertiaryColor: '#fff'
---
C4Deployment
title Deployment Diagram for Harmony System


Container(ma, "Mission Authority", "Controller", "Görev otoritesi")
    


Deployment_Node(space, "Space Segment", "Satellite Platform"){
  Container(hc, "Harmony Constellation", "Satellite", "Harmony A-B uyduları")

  Deployment_Node(ma_node, "Mission Control", "Controller"){
    Container(ma, "Mission Authority", "Controller", "Görev otoritesi")
    Container(ohb, "S/C Prime OHB", "Prime Contractor", "Uydu ana yüklenicisi")
  }
}

Deployment_Node(ground, "Harmony Ground Segment", "Ground Data Center"){
  
    Container(fos, "HARMONY FOS", "Flight Ops System", "Yer segmenti uçuş operasyon sistemi")

  

    Container(eofeos, "HARMONY EOF-EOS", "Data Processing", "Yer segmenti veri işleme ve arşiv sistemi")



}

Deployment_Node(aux, "AUX Boundary", "External Data Providers"){
    Container(auxp, "AUX Providers", "DEM, others", "Harici veri sağlayıcılar")
    Container(tr, "Transponders", "Transponder", "Transponder kaynakları")

}
Deployment_Node(s1_aux, "Sentinel-1 Data Source", "Sentinel-1"){
    Container(s1, "Sentinel-1 Data", "Data Source", "Sentinel-1 veri kaynağı")
    Container(s1fos, "S1-FOS", "Sentinel-1 FOS", "Sentinel-1 uçuş operasyon sistemi")
    Container(s1eof, "S1-EOF-CSC", "Sentinel-1 EOF", "Sentinel-1 yer segmenti")
}
Deployment_Node(users, "User Boundary", "User Devices"){
    Person(user1, "Expert User", "OQCP, PLSO gibi uzman kullanıcılar")
    Person(user2, "Commissioning User", "Kullanıcılar/Experts")
}




Rel(hc, fos, "[1] TM/TC S-Band Link")
Rel(hc, eofeos, "[2] Ka-Band Link; Instrument Data")

Rel(ohb, ma, "[12]")
Rel(ma, fos, "[12]")
Rel(ma, eofeos, "[12]")
Rel(eofeos, ma, "[12]")
Rel(ohb, fos, "[10] FOS ile iletişim")
Rel(ohb, eofeos, "[9] EOF-EOS ile iletişim")
Rel(eofeos, fos, "[3] Mission Planning, HKTM Data")
Rel(fos, eofeos, "[4] Mission Planning, Orbit, Maneuver Plan")
Rel(auxp, eofeos, "[5]")
Rel(tr, eofeos, "[11] Transponder verisi")
Rel(eofeos, tr, "[11] Transponder verisi")

Rel(s1, eofeos, "[14] Sentinel-1 verisi")
Rel(eofeos, user2, "[6] Data Products")
Rel(user2, eofeos, "[7] UserService Requests")
Rel(s1eof, eofeos, "[15] S1 Data, Metadata, Orbit, GNSS, Gyros")
Rel(s1fos, fos, "[17] S1 Predicted Orbit, Maneuver Plan, Anomaly Report")
Rel(fos, user1, "[8] HKTM/TM/TC Browsing, Export, Visualization")



UpdateElementStyle(space, $borderColor="#1976d2", $direction="TB")
UpdateElementStyle(ground, $borderColor="#c2185b", $direction="LR")
UpdateElementStyle(plc, $borderColor="#388e3c", $direction="RL")
UpdateElementStyle(b3, $borderColor="#388e3c", $direction="BT")